version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
    environment:
      POSTGRES_USER: imboyo
      POSTGRES_PASSWORD: ayyu230686
      POSTGRES_DB: main
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fresh_rss:
    image: freshrss/freshrss:latest
    container_name: fresh_rss
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      TZ: Asia/Kuala_Lumpur
      CRON_MIN: '*/20'
      POSTGRES_USER: imboyo
      POSTGRES_PASSWORD: ayyu230686
      POSTGRES_DB: main
    volumes:
      - freshrss-data:/var/www/FreshRSS/data
      - freshrss-extension:/var/www/FreshRSS/extensions

volumes:
  postgres-data:
  freshrss-data:
  freshrss-extension:

